/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventario;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Richie
 */
public class Alta extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Alta() {
        initComponents();
        rdTipo.add(rdOrdinaria);
        rdTipo.add(rdExtraordinaria);
        rdTipo.add(rdAlcance);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        archivoDigital = new javax.swing.JFileChooser();
        rdTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btSalir = new javax.swing.JButton();
        btConsulta = new javax.swing.JButton();
        btAlta = new javax.swing.JButton();
        btInicio = new javax.swing.JButton();
        btModificar = new javax.swing.JButton();
        nombre = new javax.swing.JLabel();
        numTrabajador = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cNumGac = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cPagEje = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdOrdinaria = new javax.swing.JRadioButton();
        rdExtraordinaria = new javax.swing.JRadioButton();
        rdAlcance = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cFecEje = new com.toedter.calendar.JDateChooser();
        cNumTom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btArchivoDigital = new javax.swing.JButton();
        cArcDig = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        cFecRec = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        cPerEnt = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        cNumEje = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cEjeHem = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cOrdImp = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        cbDirector = new javax.swing.JCheckBox();
        cbHemeroteca = new javax.swing.JCheckBox();
        cbRuta = new javax.swing.JCheckBox();
        cbModulo = new javax.swing.JCheckBox();
        cbSuscripciones = new javax.swing.JCheckBox();
        btLimpiar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        cDirector = new javax.swing.JTextField();
        cHemeroteca = new javax.swing.JTextField();
        cRuta = new javax.swing.JTextField();
        cModulo = new javax.swing.JTextField();
        cSuscripciones = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alta");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hemeroteca de la Editora de Gobierno");

        btSalir.setBackground(new java.awt.Color(255, 255, 255));
        btSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSalir.setText("Salir");
        btSalir.setBorderPainted(false);
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btConsulta.setBackground(new java.awt.Color(255, 255, 255));
        btConsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btConsulta.setText("Consulta");
        btConsulta.setBorderPainted(false);
        btConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultaActionPerformed(evt);
            }
        });

        btAlta.setBackground(new java.awt.Color(255, 255, 255));
        btAlta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btAlta.setText("Alta");
        btAlta.setBorderPainted(false);
        btAlta.setEnabled(false);
        btAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltaActionPerformed(evt);
            }
        });

        btInicio.setBackground(new java.awt.Color(255, 255, 255));
        btInicio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btInicio.setText("Inicio");
        btInicio.setBorderPainted(false);
        btInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicioActionPerformed(evt);
            }
        });

        btModificar.setBackground(new java.awt.Color(255, 255, 255));
        btModificar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btModificar.setText("Modificar");
        btModificar.setBorderPainted(false);
        btModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarActionPerformed(evt);
            }
        });

        nombre.setText("Bienvenido");

        numTrabajador.setText("12345");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numTrabajador)
                .addGap(18, 18, 18)
                .addComponent(btInicio)
                .addGap(18, 18, 18)
                .addComponent(btAlta)
                .addGap(18, 18, 18)
                .addComponent(btConsulta)
                .addGap(18, 18, 18)
                .addComponent(btModificar)
                .addGap(18, 18, 18)
                .addComponent(btSalir)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalir)
                    .addComponent(jLabel5)
                    .addComponent(btConsulta)
                    .addComponent(btAlta)
                    .addComponent(btInicio)
                    .addComponent(btModificar)
                    .addComponent(nombre)
                    .addComponent(numTrabajador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(128, 128, 128));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos de Gaceta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Número de gaceta:");

        cNumGac.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cNumGac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNumGacKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Páginas del ejemplar:");

        cPagEje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cPagEje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPagEjeKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Tipo:");

        rdOrdinaria.setBackground(new java.awt.Color(255, 255, 255));
        rdOrdinaria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdOrdinaria.setText("Ordinaria");
        rdOrdinaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdOrdinariaMouseClicked(evt);
            }
        });
        rdOrdinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdOrdinariaActionPerformed(evt);
            }
        });

        rdExtraordinaria.setBackground(new java.awt.Color(255, 255, 255));
        rdExtraordinaria.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdExtraordinaria.setText("Extraordinaria");
        rdExtraordinaria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdExtraordinariaMouseClicked(evt);
            }
        });
        rdExtraordinaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdExtraordinariaActionPerformed(evt);
            }
        });

        rdAlcance.setBackground(new java.awt.Color(255, 255, 255));
        rdAlcance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdAlcance.setText("Alcance");
        rdAlcance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdAlcanceMouseClicked(evt);
            }
        });
        rdAlcance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdAlcanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(rdOrdinaria)
                                .addGap(112, 112, 112)
                                .addComponent(rdExtraordinaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(143, 143, 143)
                                .addComponent(rdAlcance))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(cPagEje, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cNumGac)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(464, 464, 464))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cNumGac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cPagEje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdOrdinaria)
                    .addComponent(rdExtraordinaria)
                    .addComponent(rdAlcance))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Fecha del ejemplar:");

        cFecEje.setToolTipText("");
        cFecEje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cFecEje.setMaxSelectableDate(new java.util.Date(4134006074000L));
        cFecEje.setMinSelectableDate(new java.util.Date(-2177425330000L));
        cFecEje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cFecEjeKeyTyped(evt);
            }
        });

        cNumTom.setEditable(false);
        cNumTom.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cNumTom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNumTomKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Archivo digital:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Número de tomo:");

        btArchivoDigital.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btArchivoDigital.setText("Seleccionar archivo");
        btArchivoDigital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btArchivoDigitalActionPerformed(evt);
            }
        });

        cArcDig.setEditable(false);
        cArcDig.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cNumTom, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cFecEje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(btArchivoDigital)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cArcDig, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cFecEje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btArchivoDigital)
                    .addComponent(cArcDig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cNumTom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(128, 128, 128));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Recepción");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Fecha de recepción:");

        cFecRec.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cFecRec.setMaxSelectableDate(new java.util.Date(4134006112000L));
        cFecRec.setMinSelectableDate(new java.util.Date(-2177425292000L));
        cFecRec.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cFecRecKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Persona quién entrega:");

        cPerEnt.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cPerEnt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cPerEntKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cFecRec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cPerEnt)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(0, 398, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cFecRec, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cPerEnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Número de ejemplares:");

        cNumEje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cNumEje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cNumEjeKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Ejemplares en hemeroteca:");

        cEjeHem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cEjeHem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cEjeHemKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Cantidad de orden de impresión:");

        cOrdImp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cOrdImp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cOrdImpKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cOrdImp, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cNumEje, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cEjeHem, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cNumEje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cEjeHem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cOrdImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Entregado a:");

        cbDirector.setBackground(new java.awt.Color(255, 255, 255));
        cbDirector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbDirector.setText("Director");

        cbHemeroteca.setBackground(new java.awt.Color(255, 255, 255));
        cbHemeroteca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbHemeroteca.setText("Hemeroteca");

        cbRuta.setBackground(new java.awt.Color(255, 255, 255));
        cbRuta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbRuta.setText("Ruta");

        cbModulo.setBackground(new java.awt.Color(255, 255, 255));
        cbModulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbModulo.setText("Módulo");

        cbSuscripciones.setBackground(new java.awt.Color(255, 255, 255));
        cbSuscripciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbSuscripciones.setText("Suscripciones");

        btLimpiar.setBackground(new java.awt.Color(128, 128, 128));
        btLimpiar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btLimpiar.setText("Limpiar campos");
        btLimpiar.setPreferredSize(new java.awt.Dimension(220, 46));
        btLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpiarActionPerformed(evt);
            }
        });

        btGuardar.setBackground(new java.awt.Color(128, 128, 128));
        btGuardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btGuardar.setText("Guardar registro");
        btGuardar.setPreferredSize(new java.awt.Dimension(220, 46));
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Director:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Hemeroteca:");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Ruta:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Módulo:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Suscripciones:");

        cDirector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cDirector.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cDirectorKeyTyped(evt);
            }
        });

        cHemeroteca.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cHemeroteca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cHemerotecaKeyTyped(evt);
            }
        });

        cRuta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cRuta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cRutaKeyTyped(evt);
            }
        });

        cModulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cModulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cModuloKeyTyped(evt);
            }
        });

        cSuscripciones.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cSuscripciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cSuscripcionesKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbDirector)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(cDirector, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(299, 299, 299))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbHemeroteca)
                            .addComponent(jLabel17)
                            .addComponent(cHemeroteca, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbRuta)
                            .addComponent(jLabel18)
                            .addComponent(cRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(cbModulo)
                            .addComponent(cModulo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbSuscripciones)
                            .addComponent(jLabel20)
                            .addComponent(cSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDirector)
                            .addComponent(cbHemeroteca))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cHemeroteca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(cbSuscripciones)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(cSuscripciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(cbRuta)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(cRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(cbModulo)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addComponent(cModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1250, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicioActionPerformed
        // TODO add your handling code here:
        Index vent = new Index();
        Index.nombre.setText(nombre.getText());
        Index.numTrabajador.setText(numTrabajador.getText());
        vent.setVisible(true);
        vent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btInicioActionPerformed

    private void btAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltaActionPerformed
        // TODO add your handling code here:
        Alta vent = new Alta();
        Alta.nombre.setText(nombre.getText());
        Alta.numTrabajador.setText(numTrabajador.getText());
        vent.setVisible(true);
        vent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btAltaActionPerformed

    private void btConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultaActionPerformed
        // TODO add your handling code here:
        Consulta vent = new Consulta();
        Consulta.nombre.setText(nombre.getText());
        Consulta.numTrabajador.setText(numTrabajador.getText());
        vent.setVisible(true);
        vent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btConsultaActionPerformed

    private void btModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarActionPerformed
        // TODO add your handling code here:
        Modificacion vent = new Modificacion();
        Modificacion.nombre.setText(nombre.getText());
        Modificacion.numTrabajador.setText(numTrabajador.getText());
        vent.setVisible(true);
        vent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btModificarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        // TODO add your handling code here:
        Login vent = new Login();
        vent.setVisible(true);
        vent.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btSalirActionPerformed

    private void btArchivoDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btArchivoDigitalActionPerformed
        // TODO add your handling code here:
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files (*.pdf)", "pdf");
        archivoDigital.setFileFilter(filter);
        int opt = archivoDigital.showOpenDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            System.out.println(archivoDigital.getSelectedFile().getName()); //Nombre
            System.out.println(archivoDigital.getSelectedFile().getPath()); //Ruta
            cArcDig.setText(archivoDigital.getSelectedFile().getPath());
        }
    }//GEN-LAST:event_btArchivoDigitalActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        if (Verificar() == 1) {
            int opcion = JOptionPane.showConfirmDialog(null, "Los datos están correctos?", "REGISTRO", JOptionPane.YES_NO_OPTION);
            if (opcion == 0) {
                Gaceta gac = new Gaceta();
                gac.setNumeroGaceta(Integer.parseInt(cNumGac.getText()));
                gac.setPaginasEjemplar(Integer.parseInt(cPagEje.getText()));

                if (rdOrdinaria.isSelected()) {
                    gac.setTipo("Ordinaria");
                    gac.setNumeroTomo(0);
                }
                if (rdExtraordinaria.isSelected()) {
                    gac.setTipo("Extraordinaria");
                    gac.setNumeroTomo(Integer.parseInt(cNumTom.getText()));
                }
                if (rdAlcance.isSelected()) {
                    gac.setTipo("Alcance");
                    gac.setNumeroTomo(0);
                }

                gac.setFechaEjemplar(cFecEje.getDate());
                gac.setArchivoDigital(cArcDig.getText());
                gac.setFechaRecepcion(cFecRec.getDate());
                gac.setPersona(cPerEnt.getText());
                gac.setNumeroEjemplares(Integer.parseInt(cNumEje.getText()));
                gac.setEjemplaresHemeroteca(Integer.parseInt(cEjeHem.getText()));
                gac.setEntregadaDirector(cbDirector.isSelected());
                gac.setEntregadaHemeroteca(cbHemeroteca.isSelected());
                gac.setEntregadaRuta(cbRuta.isSelected());
                gac.setEntregadaModulo(cbModulo.isSelected());
                gac.setEntregadaSuscripciones(cbSuscripciones.isSelected());

                if (Validar(gac) == 1) {
                    Registrar(gac);
                    Historial(gac);
                    JOptionPane.showMessageDialog(null, "Se realizó el registro", "REGISTRO", JOptionPane.INFORMATION_MESSAGE);

                    String usuNom = nombre.getText();
                    String usuNum = numTrabajador.getText();
                    Alta vent = new Alta();
                    Alta.nombre.setText(usuNom);
                    Alta.numTrabajador.setText(usuNum);
                    vent.setVisible(true);
                    vent.setLocationRelativeTo(null);
                    this.dispose();
                }
            }
            if (opcion == 1) {
                JOptionPane.showMessageDialog(null, "No se realizó el registro", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpiarActionPerformed
        // TODO add your handling code here:
        cNumGac.setText(null);
        cPagEje.setText(null);
        rdTipo.clearSelection();
        cFecEje.setDate(null);
        cArcDig.setText(null);
        cNumTom.setEditable(false);
        cNumTom.setText(null);
        cFecRec.setDate(null);
        cPerEnt.setText(null);
        cNumEje.setText(null);
        cEjeHem.setText(null);
        cbDirector.setSelected(false);
        cbHemeroteca.setSelected(false);
        cbRuta.setSelected(false);
        cbModulo.setSelected(false);
        cbSuscripciones.setSelected(false);
        
        cOrdImp.setText(null);
        cDirector.setText(null);
        cHemeroteca.setText(null);
        cRuta.setText(null);
        cModulo.setText(null);
        cSuscripciones.setText(null);
    }//GEN-LAST:event_btLimpiarActionPerformed

    private void cNumGacKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNumGacKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cNumGacKeyTyped

    private void cNumTomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNumTomKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cNumTomKeyTyped

    private void cPagEjeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPagEjeKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cPagEjeKeyTyped

    private void cNumEjeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cNumEjeKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cNumEjeKeyTyped

    private void cEjeHemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cEjeHemKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cEjeHemKeyTyped

    private void cPerEntKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cPerEntKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < 'A') || (c > 'Z')) && ((c < 'a') || (c > 'z')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cPerEntKeyTyped

    private void cFecEjeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cFecEjeKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_SLASH)) {
            evt.consume();
        }
    }//GEN-LAST:event_cFecEjeKeyTyped

    private void cFecRecKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cFecRecKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE) && (c != KeyEvent.VK_SLASH)) {
            evt.consume();
        }
    }//GEN-LAST:event_cFecRecKeyTyped

    private void rdOrdinariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdOrdinariaMouseClicked
        // TODO add your handling code here:
        cNumTom.setEditable(false);
        cNumTom.setText("");
    }//GEN-LAST:event_rdOrdinariaMouseClicked

    private void rdOrdinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdOrdinariaActionPerformed
        // TODO add your handling code here:
        cNumTom.setEditable(false);
        cNumTom.setText("");
    }//GEN-LAST:event_rdOrdinariaActionPerformed

    private void rdExtraordinariaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdExtraordinariaMouseClicked
        // TODO add your handling code here:
        cNumTom.setEditable(true);
    }//GEN-LAST:event_rdExtraordinariaMouseClicked

    private void rdExtraordinariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdExtraordinariaActionPerformed
        // TODO add your handling code here:
        cNumTom.setEditable(true);
    }//GEN-LAST:event_rdExtraordinariaActionPerformed

    private void rdAlcanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdAlcanceMouseClicked
        // TODO add your handling code here:
        cNumTom.setEditable(false);
        cNumTom.setText("");
    }//GEN-LAST:event_rdAlcanceMouseClicked

    private void rdAlcanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdAlcanceActionPerformed
        // TODO add your handling code here:
        cNumTom.setEditable(false);
        cNumTom.setText("");
    }//GEN-LAST:event_rdAlcanceActionPerformed

    private void cDirectorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cDirectorKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cDirectorKeyTyped

    private void cHemerotecaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cHemerotecaKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cHemerotecaKeyTyped

    private void cRutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cRutaKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cRutaKeyTyped

    private void cModuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cModuloKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cModuloKeyTyped

    private void cSuscripcionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cSuscripcionesKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cSuscripcionesKeyTyped

    private void cOrdImpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cOrdImpKeyTyped
        // TODO add your handling code here:
        Character c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_cOrdImpKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser archivoDigital;
    private javax.swing.JButton btAlta;
    private javax.swing.JButton btArchivoDigital;
    private javax.swing.JButton btConsulta;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btInicio;
    private javax.swing.JButton btLimpiar;
    private javax.swing.JButton btModificar;
    private javax.swing.JButton btSalir;
    private javax.swing.JTextField cArcDig;
    private javax.swing.JTextField cDirector;
    private javax.swing.JTextField cEjeHem;
    private com.toedter.calendar.JDateChooser cFecEje;
    private com.toedter.calendar.JDateChooser cFecRec;
    private javax.swing.JTextField cHemeroteca;
    private javax.swing.JTextField cModulo;
    private javax.swing.JTextField cNumEje;
    private javax.swing.JTextField cNumGac;
    private javax.swing.JTextField cNumTom;
    private javax.swing.JTextField cOrdImp;
    private javax.swing.JTextField cPagEje;
    private javax.swing.JTextField cPerEnt;
    private javax.swing.JTextField cRuta;
    private javax.swing.JTextField cSuscripciones;
    private javax.swing.JCheckBox cbDirector;
    private javax.swing.JCheckBox cbHemeroteca;
    private javax.swing.JCheckBox cbModulo;
    private javax.swing.JCheckBox cbRuta;
    private javax.swing.JCheckBox cbSuscripciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JLabel nombre;
    public static javax.swing.JLabel numTrabajador;
    private javax.swing.JRadioButton rdAlcance;
    private javax.swing.JRadioButton rdExtraordinaria;
    private javax.swing.JRadioButton rdOrdinaria;
    private javax.swing.ButtonGroup rdTipo;
    // End of variables declaration//GEN-END:variables

    public int Verificar() {
        if (cNumGac.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Número de gaceta está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cPagEje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Páginas del ejemplar está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (!rdOrdinaria.isSelected() && !rdExtraordinaria.isSelected() && !rdAlcance.isSelected()) {
            JOptionPane.showMessageDialog(null, "Tipo no está seleccionado", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cNumTom.getText().isEmpty() && rdExtraordinaria.isSelected()) {
            JOptionPane.showMessageDialog(null, "Gaceta de tipo Extraordinario debe llevar un Número de tomo", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cFecEje.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Fecha del ejemplar está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cArcDig.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Archivo digital está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cFecRec.getDate() == null) {
            JOptionPane.showMessageDialog(null, "Fecha de recepción está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cPerEnt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Persona quién entrega está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cNumEje.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Número de ejemplares está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cEjeHem.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ejemplares en hemeroteca está vacío", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if (cFecEje.getDate().after(cFecRec.getDate())) {
            JOptionPane.showMessageDialog(null, "Fecha de recepción está antes de la Fecha del ejemplar", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        if ((Integer.parseInt(cNumEje.getText())) < (Integer.parseInt(cEjeHem.getText()))) {
            JOptionPane.showMessageDialog(null, "Número de ejemplares es menor a Ejemplares en hemeroteca", "ERROR", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
        return 1;
    }

    public void Registrar(Gaceta gac) {
        try {
            MySQLConnection bd = new MySQLConnection();
            Connection c = bd.Conectar();
            PreparedStatement pst;
            String sql = "INSERT INTO gacetas (numeroGaceta, paginasEjemplar, tipo, fechaEjemplar, archivoDigital, numeroTomo, fechaRecepcion, persona,"
                    + "numeroEjemplares, ejemplaresHemeroteca, entregadaDirector, entregadaHemeroteca, entregadaRuta, entregadaModulo,"
                    + "entregadaSuscripciones) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = c.prepareStatement(sql);
            pst.setInt(1, gac.getNumeroGaceta());
            pst.setInt(2, gac.getPaginasEjemplar());
            pst.setString(3, gac.getTipo());
            pst.setString(4, new SimpleDateFormat("yyyy/MM/dd").format(gac.getFechaEjemplar()));
            pst.setString(5, gac.getArchivoDigital());
            pst.setInt(6, gac.getNumeroTomo());
            pst.setString(7, new SimpleDateFormat("yyyy/MM/dd").format(gac.getFechaRecepcion()));
            pst.setString(8, gac.getPersona());
            pst.setInt(9, gac.getNumeroEjemplares());
            pst.setInt(10, gac.getEjemplaresHemeroteca());
            pst.setBoolean(11, gac.isEntregadaDirector());
            pst.setBoolean(12, gac.isEntregadaHemeroteca());
            pst.setBoolean(13, gac.isEntregadaRuta());
            pst.setBoolean(14, gac.isEntregadaModulo());
            pst.setBoolean(15, gac.isEntregadaSuscripciones());
            pst.execute();
            bd.Desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            MySQLConnection bd = new MySQLConnection();
            bd.Desconectar();
        }
    }

    public int Validar(Gaceta gac) {
        try {
            MySQLConnection bd = new MySQLConnection();
            Connection c = bd.Conectar();
            ResultSet rs;
            PreparedStatement pst;
            String sql = "SELECT * FROM gacetas WHERE numeroGaceta = ? and tipo = ? and numeroTomo = ? and fechaEjemplar = ?";
            pst = c.prepareStatement(sql);
            pst.setInt(1, gac.getNumeroGaceta());
            pst.setString(2, gac.getTipo());
            pst.setInt(3, gac.getNumeroTomo());
            pst.setString(4, new SimpleDateFormat("yyyy/MM/dd").format(gac.getFechaEjemplar()));
            rs = pst.executeQuery();

            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Esta gaceta ya fue ingresada, verifique los datos", null, JOptionPane.ERROR_MESSAGE);
                bd.Desconectar();
                return 0;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            MySQLConnection bd = new MySQLConnection();
            bd.Desconectar();
        }
        return 1;
    }

    public void Historial(Gaceta gac) {
        try {
            MySQLConnection bd = new MySQLConnection();
            Connection c = bd.Conectar();
            PreparedStatement pst;
            String sql = "INSERT INTO altas (numeroGaceta, tipo, numeroTomo, fechaEjemplar, ejemplares, nombre,"
                    + "fechaAlta) VALUES (?,?,?,?,?,?,now())";
            pst = c.prepareStatement(sql);
            pst.setInt(1, gac.getNumeroGaceta());
            pst.setString(2, gac.getTipo());
            pst.setInt(3, gac.getNumeroTomo());
            pst.setString(4, new SimpleDateFormat("yyyy/MM/dd").format(gac.getFechaEjemplar()));
            pst.setInt(5, gac.getEjemplaresHemeroteca());
            pst.setString(6, nombre.getText());
            pst.execute();
            bd.Desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Alta.class.getName()).log(Level.SEVERE, null, ex);
            MySQLConnection bd = new MySQLConnection();
            bd.Desconectar();
        }
    }
}
